package com.myspace.demo20210321;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Reservation implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Reservation() {
    }




}